apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloWeb3.fullname" . }}
  labels:
    {{- include "helloWeb3.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helloWeb3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "helloWeb3.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helloWeb3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: helloweb3
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              initialDelaySeconds: 10
              periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
              initialDelaySeconds: 5
              periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
