apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.0.6
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GFSECURITYADMINPASSWORD
            - name: GF_SERVER_PROTOCOL
              value: https
            - name: GF_SERVER_CERT_FILE
              value: /etc/grafana/ssl/grafana.crt
            - name: GF_SERVER_CERT_KEY
              value: /etc/grafana/ssl/grafana.key
          volumeMounts:
            - name: grafana-ssl
              mountPath: "/etc/grafana/ssl"
              readOnly: true
      volumes:
        - name: grafana-ssl
          secret:
            secretName: example-com-tls
