---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: default
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: default
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: letsencrypt-prod
  commonName: 35.241.149.229

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.0.6
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: GFSECURITYADMINPASSWORD
            - name: GF_SERVER_PROTOCOL
              value: https
            - name: GF_SERVER_CERT_FILE
              value: /etc/grafana/ssl/grafana.crt
            - name: GF_SERVER_CERT_KEY
              value: /etc/grafana/ssl/grafana.key
          volumeMounts:
            - name: grafana-ssl
              mountPath: "/etc/grafana/ssl"
              readOnly: true
      volumes:
        - name: grafana-ssl
          secret:
            secretName: grafana-tls-secret
