apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloWeb3.fullname" . }}
  labels:
    {{- include "helloWeb3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helloWeb3.selectorLabels" . | nindent 4 }}

replicaCount: 1

image:
  repository: europe-west4-docker.pkg.dev/dotted-lens-412717/prachtig/helloweb3
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "3000"

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 3000
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: POLYGONSCAN_API_KEY
    valueFrom:
      secretKeyRef:
        name: polygonscan-api-key
        key: POLYGONSCAN_API_KEY
