name: Build and Deploy to GKE with Terraform and Helm

on:
  push:
    branches:
      - main

jobs:
  setup-gke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud credentials
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: dotted-lens-412717
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build Docker Image
        run: docker build -t gcr.io/dotted-lens-412717/prachtig/helloweb3:${{ github.sha }} .

      - name: Push Docker Image to GCR
        run: docker push gcr.io/dotted-lens-412717/prachtig/helloweb3:${{ github.sha }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials kubernetes-cluster --zone europe-west1-d --project dotted-lens-412717

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.5.2'

      - name: Deploy to GKE using Helm
        run: |
          helm upgrade --install helloweb3 ./helm/helloweb3 --namespace default \
            --set image.repository=gcr.io/dotted-lens-412717/prachtig/helloweb3 \
            --set image.tag=${{ github.sha }}
