name: 'Build, Deploy to GCP with Terraform and Helm'

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: dotted-lens-412717
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      # Update gcloud, install kubectl and gke-gcloud-auth-plugin
      - name: Install kubectl and gke-gcloud-auth-plugin
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk-kubectl google-cloud-sdk-gke-gcloud-auth-plugin

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      # Terraform Init and Apply
      - name: Terraform Init and Apply
        run: |
          terraform init ./terraform
          terraform apply -auto-approve ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Configure Docker, Build and Push Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=32f601f
          docker build -t europe-west4-docker.pkg.dev/dotted-lens-412717/prachtig/helloweb3:$IMAGE_TAG .
          docker push europe-west4-docker.pkg.dev/dotted-lens-412717/prachtig/helloweb3:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet

      # Install Helm
      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Helm Lint
      - name: Helm Lint
        run: helm lint ./helm/helloWeb3

      # Get GKE credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials kubernetes-cluster --zone europe-west1-d --project dotted-lens-412717

      # Helm Deploy
      - name: Helm Deploy
        run: |
          helm upgrade --install helloWeb3 ./helm/helloWeb3 \
            --set image.repository=europe-west4-docker.pkg.dev/dotted-lens-412717/prachtig/helloweb3 \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set api.polygonscanApiKey=${{ secrets.POLYGONSCAN_API_KEY }}
