name: 'Build, Deploy to GCP with Terraform and Helm'

on:
  push:
    branches:
      - main

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud credentials
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Terraform Refresh
        run: terraform refresh
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  build-and-deploy:
    needs: setup-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud credentials (Again for Docker Push)
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Configure Docker and Build Image
        run: |
          IMAGE_TAG=$(git rev-parse HEAD | cut -c1-7)
          docker build -t europe-west4-docker.pkg.dev/dotted-lens-412717/prachtig/helloweb3:$IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet

      - name: Push Docker Image to GAR
        run: docker push europe-west4-docker.pkg.dev/dotted-lens-412717/prachtig/helloweb3:${{ env.IMAGE_TAG }}

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Helm Deploy
        run: |
          helm upgrade --install helloWeb3 ./helm/helloWeb3 --set image.repository=europe-west4-docker.pkg.dev/dotted-lens-412717/prachtig/helloweb3 --set image.tag=${{ env.IMAGE_TAG }}
