name: 'Build, Deploy to GCP with Terraform'

on:
  push:
    branches:
      - main

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  build:
    needs: setup-infrastructure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t gcr.io/dotted-lens-412717/helloweb3:$(git rev-parse --short HEAD) .

    - name: Setup GCP Credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: Push Docker image
      run: docker push gcr.io/dotted-lens-412717/helloweb3:$(git rev-parse --short HEAD)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup GCP Credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials helloweb3 --region southamerica-east1
        helm upgrade --install helloweb3 ./helm/helloweb3 --set image=gcr.io/dotted-lens-412717/helloweb3:$(git rev-parse --short HEAD)
